### ISSUE TITLE
Description and icon

### ISSUE THREAD

**Issue by eried** [firetunes/easel-apps#1]
I know is a pain in the ass but do you have those? 

I could create them for the missing apps (I was going to install all the apps in Easel) mainly because I think it is a good excercise to learn the super undocumented easel API

**Comment by eried** [comment]
Additionally, I guess you use API 2.0?

**Comment by firetunes** [comment]
Yes I'm using API 2.0

I could add some of the icons and descriptions. But a lot of the unapproved ones don't have official icons or descriptions yet.

**Comment by firetunes** [comment]
Icons and descriptions added where available. I didn't have descriptions or icons for all of the apps.
